### ISSUE TITLE
Redirect to login page if user is not logged in

### ISSUE THREAD

**Issue by Rabia23** [mgaby25/django-postman-sample#2]
For now, if we access the inbox url `http://127.0.0.1:8000/messages/inbox/ ` without login then it throws `Page Not Found` error. 

see screenshot:
<img width="1233" alt="screen shot 2018-10-13 at 3 21 14 pm" src="https://user-images.githubusercontent.com/13939335/46904323-cf9baf80-cefb-11e8-8f26-91d8c2d38184.png">

Is there any way that we can redirect to the login page instead of redirecting to  `Page Not Found` page?

**Comment by gmuj** [comment]
@Rabia23 Fixed now....however this is just a sample project and it's really old, I was just playing around with postman to learn.

**Comment by Rabia23** [comment]
Hi @mgaby25,

Thank you for taking this thing into your consideration. I was also learning the postman.
